# Generated by Django 4.2.6 on 2024-01-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_otp_last_email_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempt_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='attempt_remain',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
