# Generated by Django 4.2.6 on 2024-01-04 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_otp_last_email_send_alter_otp_last_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Verified',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_otp', models.CharField(blank=True, max_length=60, null=True)),
                ('last_email_send', models.IntegerField(blank=True, max_length=50, null=True)),
                ('email_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('blocked', models.BooleanField(blank=True, default=False, null=True)),
                ('attempt_remain', models.IntegerField(blank=True, null=True)),
                ('attempt_level', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_conform',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
