# Generated by Django 4.2.6 on 2024-01-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_email_verified_remove_user_email_conform_delete_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_verified',
            old_name='attempt_level',
            new_name='email_attempt_level',
        ),
        migrations.AddField(
            model_name='email_verified',
            name='last_otp_input_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email_verified',
            name='otp_attempt_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email_verified',
            name='otp_input_blocked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='email_verified',
            name='last_email_send',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
