# Generated by Django 4.2.6 on 2024-01-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_rename_attempt_level_email_verified_email_attempt_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_verified',
            name='direct_email_send',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
