# Generated by Django 4.2.6 on 2024-01-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_email_verified_direct_email_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_verified',
            name='once_email_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
