# Generated by Django 4.2.6 on 2024-04-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lotus/category'),
        ),
        migrations.AlterField(
            model_name='landingpagerelateddata',
            name='hero_banner',
            field=models.ImageField(blank=True, null=True, upload_to='lotus/landingPageRelatedData'),
        ),
        migrations.AlterField(
            model_name='landingpagerelateddata',
            name='hero_banner_2',
            field=models.ImageField(blank=True, null=True, upload_to='lotus/landingPageRelatedData'),
        ),
        migrations.AlterField(
            model_name='landingpagerelateddata',
            name='hero_banner_20',
            field=models.ImageField(blank=True, null=True, upload_to='lotus/landingPageRelatedData'),
        ),
        migrations.AlterField(
            model_name='landingpagerelateddata',
            name='hero_banner_3',
            field=models.ImageField(blank=True, null=True, upload_to='lotus/landingPageRelatedData'),
        ),
        migrations.AlterField(
            model_name='landingpagerelateddata',
            name='hero_banner_40',
            field=models.ImageField(blank=True, null=True, upload_to='lotus/landingPageRelatedData'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lotus/productImages'),
        ),
        migrations.AlterField(
            model_name='vendorimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lotus/VendorImage'),
        ),
    ]
