# Generated by Django 4.2.6 on 2024-01-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagerelateddata',
            name='hero_2_button_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landingpagerelateddata',
            name='hero_2_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingpagerelateddata',
            name='hero_3_button_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landingpagerelateddata',
            name='hero_3_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingpagerelateddata',
            name='hero_button_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landingpagerelateddata',
            name='hero_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landingpagerelateddata',
            name='hero_banner',
            field=models.ImageField(help_text='This is First image your customer going to see. Recommended image resolution 1000*400', upload_to=''),
        ),
    ]
