# Generated by Django 4.2.6 on 2024-01-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_on_your_way_order_processing_order_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='on_your_way',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
