# Generated by Django 4.2.6 on 2024-01-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='primary_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='shippingdetails',
            old_name='address',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='shippingdetails',
            old_name='state',
            new_name='primary_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='secondary_address',
        ),
        migrations.RemoveField(
            model_name='shippingdetails',
            name='mobile',
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='mobile_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='province',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
