# Generated by Django 4.2.6 on 2024-01-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_primary_address_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_order_no',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
