# Generated by Django 4.2.6 on 2024-01-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='OrderItem',
        ),
    ]
