# Generated by Django 4.2.6 on 2024-01-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_order_options_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='notes',
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
