# Generated by Django 4.2.6 on 2024-01-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_shippingdetails_notes_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='todays_deals',
            field=models.BooleanField(default=False),
        ),
    ]
