# Generated by Django 4.2.6 on 2024-01-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_product_has_size_alter_product_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssentialInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pymary_gmail', models.EmailField(max_length=254)),
                ('pymary_gmail_app_password', models.EmailField(max_length=254)),
                ('hero_title', models.CharField(max_length=100)),
                ('hero_desc', models.CharField(max_length=300)),
                ('hero_2_title', models.CharField(max_length=100)),
                ('hero_2_desc', models.CharField(max_length=300)),
                ('hero_3_title', models.CharField(max_length=100)),
                ('hero_3_desc', models.CharField(max_length=300)),
                ('hero_banner', models.ImageField(upload_to='')),
                ('hero_banner_2', models.ImageField(upload_to='')),
                ('hero_banner_3', models.ImageField(upload_to='')),
                ('hero_banner_20', models.ImageField(upload_to='')),
                ('hero_banner_40', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='shippingdetails',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
